apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: portfolio-client-ingress
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    kubernetes.io/ingress.class: nginx
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - midden.reedgaines.com
    secretName: iam-midden-tls-secret
  rules:
  - host: midden.reedgaines.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: portfolio-client-service
            port:
              number: 80