apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: portfolio-client-ingress
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    kubernetes.io/ingress.class: nginx
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - 96.126.106.29.nip.io
    secretName: iam-tls-secret
  rules:
  - host: 96.126.106.29.nip.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: portfolio-client-service
            port:
              number: 80