apiVersion: apps/v1
kind: Deployment
metadata:
  name: portfolio-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: portfolio-client
  template:
    metadata:
      labels:
        app: portfolio-client
    spec:
      containers:
      - name: portfolio-client
        image: crymall/portfolio-client:v1
        imagePullPolicy: Always
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: portfolio-client-service
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: portfolio-client